#file: noinspection SpellCheckingInspection
packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core React & Next.js
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "@types/react": "^18.3.11"
  "@types/react-dom": "^18.3.0"
  "next": "14.2.8"

  # Build Tools
  "typescript": "^5.6.3"
  "@types/node": "^20"
  "prettier": "^3.3.3"

  # CSS & Styling
  "tailwindcss": "^3.4.13"
  "autoprefixer": "^10"
  "postcss": "^8"
  "postcss-load-config": "^6"
  "tailwind-merge": "^2.3.0"
  "tailwindcss-animate": "^1.0.7"
  "class-variance-authority": "^0.7.0"
  "clsx": "^2.1.1"

  # Radix UI Components
  "@radix-ui/react-accordion": "^1.2.7"
  "@radix-ui/react-alert-dialog": "^1.1.10"
  "@radix-ui/react-aspect-ratio": "^1.1.4"
  "@radix-ui/react-avatar": "^1.1.6"
  "@radix-ui/react-checkbox": "^1.2.2"
  "@radix-ui/react-collapsible": "^1.1.7"
  "@radix-ui/react-context-menu": "^2.2.11"
  "@radix-ui/react-dialog": "^1.1.10"
  "@radix-ui/react-dropdown-menu": "^2.1.11"
  "@radix-ui/react-hover-card": "^1.1.10"
  "@radix-ui/react-label": "^2.1.4"
  "@radix-ui/react-menubar": "^1.1.11"
  "@radix-ui/react-navigation-menu": "^1.2.9"
  "@radix-ui/react-popover": "^1.1.10"
  "@radix-ui/react-progress": "^1.1.4"
  "@radix-ui/react-radio-group": "^1.3.3"
  "@radix-ui/react-scroll-area": "^1.2.5"
  "@radix-ui/react-select": "^2.2.2"
  "@radix-ui/react-separator": "^1.1.4"
  "@radix-ui/react-slider": "^1.3.2"
  "@radix-ui/react-slot": "^1.0.2"
  "@radix-ui/react-switch": "^1.2.2"
  "@radix-ui/react-tabs": "^1.1.8"
  "@radix-ui/react-toggle": "^1.1.6"
  "@radix-ui/react-toggle-group": "^1.1.7"
  "@radix-ui/react-tooltip": "^1.2.3"

  # UI & Forms
  "lucide-react": "^0.451.0"
  "@tanstack/react-table": "^8.21.3"
  "cmdk": "^1.1.1"
  "embla-carousel-react": "^8.6.0"
  "input-otp": "^1.4.2"
  "next-themes": "^0.4.6"
  "react-day-picker": "^9.7.0"
  "react-hook-form": "^7.56.0"
  "@hookform/resolvers": "^5.0.1"
  "react-resizable-panels": "^2.1.8"
  "recharts": "^2.15.3"
  "sonner": "^2.0.3"
  "vaul": "^1.1.2"

  # Utilities
  "date-fns": "^4.1.0"
  "zod": "^3.24.3"
