packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0

# 工作区级别统一脚本（通过 pnpm -w run <script> 调用）
scripts:
  # 递归构建所有包
  build: "pnpm -r run build"
  # 递归运行测试
  test: "pnpm -r run test"
  # 全局代码检查
  lint: "eslint . --fix"
  # 统一代码格式化
  format: "prettier --write ."
  # 安装 Git 钩子
  prepare: "simple-git-hooks"
