packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
