'use client'

import Head from 'next/head'
import {Auth} from '@supabase/auth-ui-react'
import {ThemeSupa} from '@supabase/auth-ui-shared'
import {useEffect, useState} from 'react'
import {Session} from "@supabase/supabase-js";
import {createClient} from "~/utils/supabase/component";
import BooksPage from "~/pages/books/books-page";
import {Button} from "@repo/core-ui-shadcn/components/ui/button";
import {CardTitle} from "@repo/core-ui-shadcn/components/ui/card";

export default function Home() {
  const [session, setSession] = useState<Session | null>(null)
  const supabase = createClient()

  useEffect(() => {
    supabase.auth.getSession().then(({data: {session}}) => {
      setSession(session)
    })

    const {
      data: {subscription},
    } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })

    return () => subscription.unsubscribe()
  }, [supabase])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="w-full h-full bg-200">
        {!session ? (
          <div className="min-w-full min-h-screen flex items-center justify-center">
            <div className="w-full h-full flex justify-center items-center p-4">
              <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                <CardTitle className="text-2xl text-center">Login</CardTitle>
                <Auth supabaseClient={supabase} appearance={{theme: ThemeSupa}} theme="default"/>
              </div>
            </div>
          </div>
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{minWidth: 250, maxWidth: 600, margin: 'auto'}}
          >
            <BooksPage/>
            <Button
              className="btn-black mt-12"
              onClick={async () => {
                const {error} = await supabase.auth.signOut()
                if (error) console.log('Error logging out:', error.message)
              }}
            >
              Logout
            </Button>
          </div>
        )}
      </div>
    </>
  )
}
